### ISSUE TITLE
problems with new directory structure of cabal

### ISSUE THREAD

**Issue by amigalemming** [jan-christiansen/cabal-uninstall#2]
Cabal has changed the directory structure of installed packages. I can remove package versions installed with old Cabal, but with current one (Cabal-1.20) I get something like this:

```
$ cabal-uninstall midi-alsa-0.2.1.1
Unregister the package midi-alsa-0.2.1.1 (user package)? (yes/no)yes
Delete the package directory /home/me/.cabal/lib/x86_64-linux-ghc-7.4.2? (yes/no)no 
```

**Comment by thomie** [comment]
Sorry about the noise...
